export function getResultMock() {
    return {
        _id: 'my-result-id',
        createdAt: new Date(1980, 2, 20, 10, 0, 0),
        modifiedAt: new Date(1980, 2, 20, 10, 0, 10),
        childId: 'child-id',
        kindergartenId: 'kindergarten-id',
        assessmentId: 'assessment-id',
        assessment: null,
        child: null,
        currentParams: null,
        firstMeasurementRunDate: new Date(1980, 2, 20, 10, 0, 10),
        lastMeasurementRunDate: new Date(1980, 2, 20, 10, 0, 10),
        firstMeasurementPendelumRunDate: new Date(1980, 2, 20, 10, 0, 10),
        lastMeasurementPendelumRunDate: new Date(1980, 2, 20, 10, 0, 10),
        firstMeasurementThrowDate: new Date(1980, 2, 20, 10, 0, 10),
        lastMeasurementThrowDate: new Date(1980, 2, 20, 10, 0, 10),
        firstMeasurementJumpDate: new Date(1980, 2, 20, 10, 0, 10),
        lastMeasurementJumpDate: new Date(1980, 2, 20, 10, 0, 10),
        firstMeasurementNote: '',
        lastMeasurementNote: '',
        firstMeasurementKindergarten: '',
        lastMeasurementKindergarten: '',
        firstMeasurementInstructor: '',
        lastMeasurementInstructor: '',
        firstMeasurementRunResult: 10,
        lastMeasurementRunResult: 10,
        firstMeasurementPendelumRunResult: 10,
        lastMeasurementPendelumRunResult: 10,
        firstMeasurementThrowResult: 10,
        lastMeasurementThrowResult: 10,
        firstMeasurementJumpResult: 10,
        lastMeasurementJumpResult: 10,
    };
}
