export const AGREEMENTS = [
    {
        _id: '',
        agreementId: '0',
        date: '2021-01-21',
        isSigned: false,
        text: 'registration-page.agreements.select-all',
    },
    {
        _id: '',
        agreementId: '1',
        date: '2021-01-21',
        isSigned: false,
        text: 'registration-page.agreements.statement',
        isRequired: true,
    },
    {
        _id: '',
        agreementId: '2',
        date: '2021-01-21',
        isSigned: false,
        text: 'registration-page.agreements.agreement2-text',
        isRequired: true,
    },
    {
        _id: '',
        agreementId: '3',
        date: '2021-01-21',
        isSigned: false,
        text: 'registration-page.agreements.agreement3-text',
        extraContent: 'registration-page.agreements.agreement3-extra-content',
        type: 'Marketing',
    },
    {
        _id: '',
        agreementId: '4',
        date: '2021-01-21',
        isSigned: false,
        text: 'registration-page.agreements.agreement4-text',
        extraContent: 'registration-page.agreements.agreement4-extra-content',
        type: 'Image',
    },
];
